<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="6" total="10" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="73302" started-at="2021-06-26T14:20:33Z" finished-at="2021-06-26T14:21:47Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="73302" started-at="2021-06-26T14:20:33Z" finished-at="2021-06-26T14:21:47Z">
      <class name="testcases.TC001HomePage">
        <test-method status="PASS" signature="init()[pri:0, instance:testcases.TC001HomePage@396f6598]" name="init" is-config="true" duration-ms="36408" started-at="2021-06-26T14:19:57Z" finished-at="2021-06-26T14:20:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="verifyImgDisplay()[pri:0, instance:testcases.TC001HomePage@396f6598]" name="verifyImgDisplay" duration-ms="846" started-at="2021-06-26T14:20:33Z" finished-at="2021-06-26T14:20:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyImgDisplay -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:testcases.TC001HomePage@396f6598]" name="closeBrowser" is-config="true" duration-ms="2670" started-at="2021-06-26T14:21:47Z" finished-at="2021-06-26T14:21:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- testcases.TC001HomePage -->
      <class name="testcases.TC003Navigation_Hubs">
        <test-method status="FAIL" signature="verifyHubsNavigation()[pri:0, instance:testcases.TC003Navigation_Hubs@27a5f880]" name="verifyHubsNavigation" duration-ms="2750" started-at="2021-06-26T14:20:50Z" finished-at="2021-06-26T14:20:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.tvo.org/current-affairs/tag/northeastrn] but found [https://www.tvo.org/current-affairs/tag/northeastern]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.tvo.org/current-affairs/tag/northeastrn] but found [https://www.tvo.org/current-affairs/tag/northeastern]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testcases.TC003Navigation_Hubs.verifyHubsNavigation(TC003Navigation_Hubs.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHubsNavigation -->
      </class> <!-- testcases.TC003Navigation_Hubs -->
      <class name="testcases.TC002Navigation_Coronavirus">
        <test-method status="PASS" signature="verifyTitle()[pri:0, instance:testcases.TC002Navigation_Coronavirus@394e1a0f]" name="verifyTitle" duration-ms="10359" started-at="2021-06-26T14:20:39Z" finished-at="2021-06-26T14:20:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitle -->
      </class> <!-- testcases.TC002Navigation_Coronavirus -->
      <class name="testcases.TC004Navigation_Kids">
        <test-method status="PASS" signature="verifyKidsNavigation()[pri:0, instance:testcases.TC004Navigation_Kids@1d29cf23]" name="verifyKidsNavigation" duration-ms="49116" started-at="2021-06-26T14:20:54Z" finished-at="2021-06-26T14:21:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyKidsNavigation -->
      </class> <!-- testcases.TC004Navigation_Kids -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
